name: build and deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_STAGE_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
        env:
          HD_NEXT_PUBLIC_BOPS_API_CAMDEN: ${{ secrets.CAMDEN_STAGE_BOPS_API_URL }}
          HD_NEXT_PUBLIC_BOPS_API_SOUTHWARK: ${{ secrets.SOUTHWARK_STAGE_BOPS_API_URL }}
          HD_NEXT_PUBLIC_BOPS_API_BUCKINGHAMSHIRE: ${{ secrets.BUCKINGHAMSHIRE_STAGE_BOPS_API_URL }}
          HD_NEXT_PUBLIC_BOPS_API_BARNET: ${{ secrets.BARNET_STAGE_BOPS_API_URL }}
          HD_SOUTHWARK_API_KEY: ${{ secrets.SOUTHWARK_STAGE_API_KEY }}
          HD_CAMDEN_API_KEY: ${{ secrets.CAMDEN_STAGE_API_KEY }}
          HD_BUCKINGHAMSHIRE_API_KEY: ${{ secrets.BUCKINGHAMSHIRE_STAGE_API_KEY }}
          HD_BARNET_API_KEY: ${{ secrets.BARNET_STAGE_API_KEY }}
