name: build and deploy

on:
  push:
    branches: ["wip-heroku"]

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_STAGING_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
        env:
          NEXT_PUBLIC_BOPS_API_CAMDEN: ${{ secrets.CAMDEN_BOPS_API_URL }}
          NEXT_PUBLIC_BOPS_API_SOUTHWARK: ${{ secrets.LAMBETH_BOPS_API_URL }}
