name: build and deploy

on:
  push:
    tags: ["release-v*.*.*"]

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v3

      - name: Deploy to Heroku Production

        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: public-index
          heroku_email: fg-dev@tpximpact.com
          usedocker: true
