# This file is part of the Digital Planning Register project.
#
# Digital Planning Register is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Digital Planning Register is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Digital Planning Register. If not, see <https://www.gnu.org/licenses/>.

name: build and deploy dev

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: "Install Heroku CLI"
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          stack: "container"
