name: build and deploy staging

# TEMPORARILY DISABLE AUTOMATIC DEPLOYMENT TO STAGING
# WCAG TESTING IN PROGRESS
on:
  push:
    # branches: ["main"]
    branches-ignore:
      - "*" # This ignores all branches, effectively disabling automatic deployment
      # TODO Remove the above line and uncomment the line above it to enable automatic deployment

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: "Install Heroku CLI"
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          stack: "container"
